apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose -f minio.yml convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: minio
  name: minio
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9001"
      port: 9001
      targetPort: 9001
  type: NodePort
  selector:
    io.kompose.service: minio
