apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f minio.yml convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f minio.yml convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/osboxes-default: "true"
        io.kompose.service: minio
    spec:
      containers:
        - image: docker.io/bitnami/minio:2024
          name: minio
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
            - containerPort: 9001
              hostPort: 9001
              protocol: TCP
      restartPolicy: Always
